### ISSUE TITLE
Odd reaction with cluster more than 1K Annotation with the same Latitude and Longitude. 

### ISSUE THREAD

**Issue by veyhong** [gunterhager/AnnotationClustering#1]
I have problem when trying to add same coordinates many time but in example show only 440 cluster. 
To re produce the bug : 
in Example/ViewController.swift
line 29:     let numberOfLocations = 1000
line 52:     a.coordinate = CLLocationCoordinate2D(latitude:  15.415599822998047, longitude: 101.57099914550781)

and then compile and run. 

the map show only 440 annotation
![simulator screen shot jun 13 2016 2 22 08 pm](https://cloud.githubusercontent.com/assets/10571492/15999785/44c042aa-3172-11e6-8934-8a85b252d705.png)

**Comment by gunterhager** [comment]
Thanks for bringing this up. I know that the Quadtree implementation used for clustering handles large numbers of annotations at the same coordinate quite suboptimal. The tree gets very deep on a single branch leading to bad performance. It might lead to other issues like the one you observed. I'll look into it.

**Comment by gunterhager** [comment]
Quad tree implementation was fixed. It did subdivide too often so that the bounding rects would get too small to fit the annotation's location in it.
