### ISSUE TITLE
How to remove annotations from cluster?

### ISSUE THREAD

**Issue by Zyg0te** [gunterhager/AnnotationClustering#2]
Hi!

Really cool clustering you have implemented. However, I'm looking for a way to remove all annotations from the cluster before I add new ones in order to avoid duplicates. 

I tried to implement this by adding this in QuadTree.swift

```
func removeAllAnnotations(){
        rootNode.removeAllAnnotations()
    }
```
And this seems to work... kinda, but not if I call it when adding annotations. 

```
 public func addAnnotations(annotations:[MKAnnotation]) {
        lock.lock()
        removeAllAnnotations()
        for annotation in annotations {
            tree.addAnnotation(annotation)
        }
        lock.unlock()
    }
    
    func removeAllAnnotations(){
        tree.removeAllAnnotations()
    }
```
I still get duplicates this way. And even if I add the `removeAllAnnotations()` call to after the `tree.addAnnotation(annotation)` call I still get plenty of annotations in my map. 

Any idea how to best implement this? I basically just want to remove all clustered annotations before adding new ones.

**Comment by gunterhager** [comment]
I don't think that you need to implement anything new in QuadTree. When i reload my annotations i use:
```
clusterManager.setAnnotations(annotations)
mapView(mapView, regionDidChangeAnimated: false)
```
Where `annotations` is an array of objects that conform to `MKAnnotation`, `clusterManager` is an instance of `ClusterManager`.

In the map view delegate: 
```
    func mapView(mapView: MKMapView, regionDidChangeAnimated animated: Bool){
        NSOperationQueue().addOperationWithBlock({
            let mapBoundsWidth = Double(self.mapView.bounds.size.width)
            let mapRectWidth = self.mapView.visibleMapRect.size.width
            let scale = mapBoundsWidth / mapRectWidth
            let annotations = self.clusterManager.clusteredAnnotationsWithinMapRect(self.mapView.visibleMapRect, withZoomScale: scale)
            self.clusterManager.displayAnnotations(annotations, mapView: self.mapView)
        })
    }
```
