### ISSUE TITLE
AnnotationClusterViewOptions does not have any effect

### ISSUE THREAD

**Issue by mlindholm** [gunterhager/AnnotationClustering#4]
Hi, this is a really nice plugin. Everything seems to work except for the AnnotationClusterViewOptions. The code below worked back when i used the FBAnnotationClusteringSwift but can't figure out why it isn't working here.

Here's a snippet from my `viewForAnnotation` method that handles the annotation cluster

```
case let cluster as AnnotationCluster:
reuseId = "Cluster"
if let clusterView = mapView.dequeueReusableAnnotationViewWithIdentifier(reuseId) as? AnnotationClusterView {
    clusterView.reuseWithAnnotation(cluster)
    return clusterView
} else {
    let options = AnnotationClusterViewOptions(smallClusterImage: "cluster_small", mediumClusterImage: "cluster_medium", largeClusterImage: "cluster_large")
    let clusterView = AnnotationClusterView(annotation: cluster, reuseIdentifier: reuseId, options: options)
    return clusterView
}
```

Thanks!

**Comment by gunterhager** [comment]
Thanks for bringing this to my attention. There was a bug in the `AnnotationClusterView` initializer. This will be fixed in the next release.
